server:
  port: 10000

spring:
  application:
    name: nacos-a2a-client-example
  ai:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-r1
    alibaba:
      a2a:
        enabled: false
        nacos:
          server-addr: 127.0.0.1:8848
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD}

# 调试日志
logging:
  level:
    root: info