server:
  port: 10000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: nacos-a2a-client-example
  ai:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
#          model: deepseek-r1
          model: qwen-plus-latest
    alibaba:
      a2a:
        enabled: false
        nacos:
          server-addr: 127.0.0.1:8848
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD}
      graph:
        observation:
          enabled: true
        arms:
          enabled: true
          tool:
            enabled: true
          model:
            capture-input: true
            capture-output: true

# 调试日志
logging:
  level:
    root: info
    com:
      alibaba:
        cloud:
          ai:
            graph: DEBUG
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      # health status check with detailed messages
#      show-details: always
#  tracing:
#    sampling:
#      # trace information with every request
#      probability: 1.0
#  observations:
#    annotations:
#      enabled: true
#  otlp:
#    tracing:
#      export:
#        enabled: true
#      endpoint: http://${STUDIO_IP}:4318/v1/traces
#    metrics:
#      export:
#        enabled: false
#    logging:
#      export:
#        enabled: false
#  opentelemetry:
#    resource-attributes:
#      service:
#        name: aliyun-helper-agent
#        version: 1.0.0
#      deployment:
#        environment: test