server:
  port: 10000

spring:
  application:
    name: nacos-a2a-client-example
  ai:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-r1

# 调试日志
logging:
  level:
    root: info