server:
  port: 9999

spring:
  application:
    name: nacos-a2a-server-example
  ai:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
#          model: deepseek-r1
          model: qwen-plus-latest
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications
    alibaba:
      a2a:
        nacos:
          server-addr: 127.0.0.1:8848
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD}
      mcp:
        nacos:
          namespace: public
          server-addr: ${NACOS_ADDRESS_ENV:127.0.0.1:8848}
          username: ${NACOS_USERNAME:nacos}
          password: ${NACOS_PASSWORD}
          client:
            enabled: true
            sse:
              connections:
                server1:
                  service-name: nacos-mcp-server-gateway
                  version: 1.0.0

# 调试日志
logging:
  level:
    root: info
    com:
      alibaba:
        cloud:
          ai:
            graph: DEBUG