server:
  port: 9999

spring:
  application:
    name: nacos-a2a-server-example
  ai:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-r1

# 调试日志
logging:
  level:
    root: info
    io:
      a2a: debug
    org:
      springframework:
        web:
          reactive: debug
    reactor:
      netty: debug