server:
  port: 9999

spring:
  application:
    name: a2s-server-example
  ai:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: deepseek-r1

    alibaba:
      a2a:
        nacos:
          username: nacos
          password: nacos