server:
  port: 18080

spring:
  application:
    name: nacos-mcp-consumer-example
  config:
    import:
      - "optional:nacos:prompt-config.json"
  nacos:
    username: nacos
    password: nacos
  ai:
    dashscope:
      api-key: ${BAILIAN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus-latest
          enable-thinking: true
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications

    alibaba:
      mcp:
        nacos:
          namespace: public
          server-addr: ${NACOS_ADDRESS_ENV:127.0.0.1:8848}
          username: nacos
          password: nacos
          client:
            enabled: true
            sse:
              connections:
                server1:
                  service-name: nacos-cluster-provider
                  version: 1.0.1
                server2:
                  service-name: nacos-mcp-server-gateway
                  version: 1.0.0
    nacos:
      prompt:
        template:
          enabled: true

# 调试日志
logging:
  level:
    root: info